- name: variables from inventory through arguments
  hosts: local
  connection: local
  tasks:
    - name: print the course information
      ansible.builtin.debug:
        msg: "Hi I am learning course is {{COURSE}} and durtahion is {{DURATION}} and trainer is {{TRAINER}}"
