- name: gathering the facts and used to install the niginx
  hosts: frontend
  become: yes
  tasks:
  - name: install the nginx if OS is redhat
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family=="RedHat"

  - name: install the nginx if os is debian
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os_family=="Debian"
  
  - name: start the nginx service 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: To check the nginx service states
    ansible.builtin.service_facts:

  - name: print nginx running status
    ansible.builtin.debug:
        msg: "Nginx running in {{inventory_hostname}}"
    when: services['nginx.service'].state == "running"


  - name: print nginx NOT running status
    ansible.builtin.debug:
        msg: "Nginx is NOT running on {{ inventory_hostname }}"
    when: services['nginx.service'].state != "running"




   