- name: gathering the facts and used to install the niginx
  hosts: frontend
  become: yes
  tasks:
  - name: install the nginx if OS is redhat
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family=="RedHat"

  - name: install the nginx if os is ubuntu
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family=="Ubuntu"




   