- name: gathering the facts and used to install the niginx
  hosts: frontend
  become: yes
  tasks:
  #To install the nginx we can use the below code
  - name: install the nginx if OS is redhat
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family=="RedHat"

  - name: install the nginx if os is debian
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os_family=="Debian"

  #to start and enable the nginx service
  
  - name: start the nginx service 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
# to check and print the status of nginx
  - name: To check the nginx service states
    ansible.builtin.service_facts:

  - name: print nginx running status
    ansible.builtin.debug:
        msg: "Nginx running in {{inventory_hostname}}"
    when: services['nginx.service'].state == "running"


  - name: print nginx NOT running status
    ansible.builtin.debug:
        msg: "Nginx is NOT running on {{ inventory_hostname }}"
    when: services['nginx.service'].state != "running"

# to stop the nginx service we can use the below code.
  - name: stop and disable the nginx 
    ansible.builtin.service:
      name: nginx
      state: stopped
      enabled: no
   