- name: gathering the facts and used to install the multiple packages using loop
  hosts: frontend
  become: yes
  tasks:
  #To install the nginx we can use the below code
  - name: install the "{{item}}" if OS is redhat
    ansible.builtin.dnf:
      name: "{{item}}"
      state: installed
    when: ansible_os_family=="RedHat"

  - name: install the "{{item}}" if os is debian
    ansible.builtin.apt:
      name: "{{item}}"
      state: installed
    when: ansible_os_family=="Debian"
    loop:
      mysql
      zip
      nginx

  #to start and enable the packages service
  
  - name: start the "{{item}}" service 
    ansible.builtin.service:
      name: "{{item}}"
      state: started
      enabled: yes
# to check and print the status of packages
  - name: To check the "{{item}}" service states
    ansible.builtin.service_facts:

  - name: print "{{item}}" running status
    ansible.builtin.debug:
        msg: "{{item}} running in {{inventory_hostname}}"
    when: services['{{item}}.service'].state == "running"


  - name: print "{{item}}" NOT running status
    ansible.builtin.debug:
        msg: "{{item}} is NOT running on {{ inventory_hostname }}"
    when: services['{{item}}.service'].state != "running"

# to stop the packahe service we can use the below code.
  - name: stop and disable the "{{item}}"" 
    ansible.builtin.service:
      name: "{{item}}"
      state: stopped
      enabled: no
   