- name: install the packages in loop mode
  hosts: frontend
  become: yes
  tasks:
  - name: install the packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: installed
    loop:
      - nginx
      - zip
      - mysql