- name: install and uninstall packages using the list at a time
  hosts: frontend
  become: yes
  tasks:
    - name: install and uninstall packages using loop
      ansible.builtin.dnf:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - { name: "nginx", state: "present"}
        - { name: "zip",state: "absent"}
        - { name: "mysql", state: "present"}