- name: convert the map to list
  hosts: local
  connection: local
  vars:
    COURSE:
      name: linux
      duration: 10HR
      mode: online
  tasks:
    - name:
        ansible.builtin.debug:
          msg: "Course: {{COURSE | dict2item}}"