- name: install nginx
  hosts: local
  connection: local
  become: yes #sudo access
  tasks:
  - name: nginx install
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: installed and running
    ansible.builtin.debug:
      msg: "Nginx started and installed"