- name: variable from file
  hosts: local
  connection: local
  var_files:
  - course.yaml
  tasks:
  - name: print the course details
    ansible.builtin.debug:
      msg: "Hello i am learning {{COURSE}}, duration{{DURATION}} and trainer is {{TRAINER}}"