- name: create the file from ansible server to node server
  hosts: local
  connection: local
  tasks:
    - name: create the file
      ansible.builtin.file:
        path: /home/ec2-user/files
        state: touch
        owner: ec2-user
        group: ec2-user
        mode: '0645'