- name: install the packages
  hosts: frontend
  become: yes
  tasks: 
  - name: show the disk partion details
    ansible.builtin.command: lsblk

  - name: increase the disk size
    ansbile.builtin.command: growpart /dev/nvme0n1 4

  - name: increase the /dev/rootVG/rootVol
    ansible.builtin.command: lvextend -L +20G /dev/RootVG/rootVol

  - name: increase /dev/rootVG/varvol
    ansible.builtin.command: lvextend -L +15G /dev/RootVG/varVol

  - name: install the list of packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: installed
    loop: 
     - python
     - nginx
     - mysql-server