- name: install the packages
  hosts: frontend
  become: yes
  tasks: 
  - name: print disk info
    ansible.builtin.debug:
      var: disk_info.stdout_lines

  - name: extend root partition
    ansible.builtin.command: growpart /dev/nvme0n1 1
    register: growpart_out
    failed_when: false

  - name: grow filesystem (XFS)
    ansible.builtin.command: xfs_growfs /
    when: growpart_out.rc == 0

  - name: install the list of packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: installed
    loop: 
     - python
     - nginx
     - mysql-server